### ISSUE TITLE
m5stack_fire/m5stack_core2  tested and core-dumped

### ISSUE THREAD

**Issue by oldsheep68** [georgik/esp32-rust-multi-target-template#1]
While trying the template, I connected my m5stack_fire / m5stack_core2 and tried it with real HW.
Unfortunately, both core dumped. 

My devices have both gyros of mpu6886 soldered. While initialization with mpu6050 driver, the device type is checked and therefore an exception is thrown.

I modified the mpu6050 library to fit for mpu6886 [https://github.com/oldsheep68/mpu6886.git].
I uploaded it also to crates.io. [https://crates.io/crates/mpu6886]
After that, the little game started to work with m5stack_fire. I didn't try the core2 device.

I do not know, if there are m5stack_fire with different accel/gyro chips soldered out there. The documentation clearly states MPU9250, but on my device, there is the mpu6886 mentioned.

**Comment by georgik** [comment]
Thank you @oldsheep68 for providing updated driver.
Your solution works out of the box. 

MPU6886 generates slightly lower values when compared to MPU6050, so I just added threshold to 0.3 instead of 1.0 to detect tilt in the example to move the sprite around the screen.
